### PR TITLE
YouTube Embed Links:   

### LINKED ISSUE #2: Get car recall video from YouTube API
Collect the Most Relevant automotive recall video from YouTube using the YEAR, MAKE, MODEL, COMPONENT, "recall"

### LINKED ISSUE #4: Build YouTube API test
Create a set of tests for returning the recall videos

### PR DESCRIPTION
**Pull request by Mr-3rd**
Created the initial structure for the YouTube API Calls. Attempted fine tuning of video returns. Ran out of YouTube Credits to make API calls.

### CODE REVIEW

**Comment by pengxuemoua** [comment]
API call successfully returns youtube video. Approved to merge into main. 

@Mr-3rd  and @amylynndee

**Comment by Mr-3rd** [comment]
@pengxuemoua & @amylynndee , please review this pull as we have completed the changes together

**Comment by amylynndee** [comment]
Code looks good, the API call returns YouTube video. We are good to merge!

**Review by amylynndee — APPROVED** [review]
Approved.

**Review by pengxuemoua — APPROVED** [review]

**Pull request merged**
