### PR TITLE
Car recall api

### LINKED ISSUE #6: Build NHTSA API Tests

### LINKED ISSUE #8: Get NHTSA car recall data from NHTSA API

### PR DESCRIPTION
**Pull request by pengxuemoua**
Working on NHTSA Api call.

-complete unit test
-add explicit error handling
-caching results

### CODE REVIEW

**Comment by pengxuemoua** [comment]
Completed:
- cache results
- sort list of dictionary objects by date in ascending order. 
- function only returns recall_results data instead of count and recall_results.
- added explicit error handling. 


Future updates:
- Complete unit tests in the future.

**Comment by pengxuemoua** [comment]
Sending to @Mr-3rd and @amylynndee for approval to merge into main.

**Review by Mr-3rd — APPROVED** [review]
I'll look into the cache options for the utility you found great job! @pengxuemoua

**Comment by amylynndee** [comment]
Your changes look good, API call works, we are good to merge!

**Review by amylynndee — APPROVED** [review]
Approved.

**Pull request merged**
