### PR TITLE
Flickr Photo API Return:  

### LINKED ISSUE #1: Get car images from Flickr API
Collect a set of images from the Flickr API with COLOR, YEAR, MAKE, MODEL

### LINKED ISSUE #3: Build Flickr API tests
Build a set of tests for getting images

### PR DESCRIPTION
**Pull request by Mr-3rd**
Initial Flickr API configuration, returns image of car from flickr.

Work to complete:
- ~URL Construction~
- Unit Testing
- Logging
- Explicit Error Handling
- Image URL caching

### CODE REVIEW

**Comment by Mr-3rd** [comment]
@pengxuemoua & @amylynndee , please review this pull as we have completed the changes together

**Comment by pengxuemoua** [comment]
API Call successfully returns photos. Approved to merge into main.

**Review by pengxuemoua — APPROVED** [review]

**Comment by Mr-3rd** [comment]
I merges the changes from the main .gitignore into the flickr branch .gitignore file

**Comment by amylynndee** [comment]
API Call successfully returns photos. Merge conflict was resolved, we're good to go.

**Pull request merged**
